require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5.3
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
